In [1]:
import pandas as pd

In [2]:
data  = pd.read_csv('/content/data_patient_cleaned (1).csv' )

data['telephone'].astype(str)


data_moamuna = pd.read_excel('/content/donn√©es_patients (1).xlsx', dtype={'ref' : str})

In [3]:
from pickle import TRUE
data_sorted  = data.sort_values(by=['ref','dateheure'] , ascending=[True , False] )
unique_data = data_sorted.drop_duplicates(subset='ref' , keep='first')

In [4]:
unique_data

,Unnamed: 0,Chun,adresse,region,cin,dateheure,dnaiss,email,nomprenom,ba,...,ref,age,telephone_extracted_from_adresse,cin_from_region,cin_from_adress,nom,prenom,predicted_gender,year_naiss,total_comment
0,0,1,NaN,NaN,NaN,2014-10-31 07:37:46,1958-01-01,0,TRIFHAT RKIA,F,...,14J1,56 ans,NaN,NaN,NaN,TRIFHAT,RKIA,F,1958,"TRAITEMENT ?: SINTROM,"
242396,242396,242815,LA LAGUNE,N398248,N398248,2024-04-24 10:24:04,1995-08-22,0,NADHAMMOU ZINEB,F,...,14J10,28 ans,NaN,N398248,NaN,NADHAMMOU,ZINEB,F,1995,"DDR: ,"
10,10,11,NaN,NaN,NaN,2014-10-31 09:12:00,1973-01-01,0,DAKHISSI MOHAMED,M,...,14J11,41 ans,NaN,NaN,NaN,DAKHISSI,MOHAMED,M,1973,"Abstinence: 3 jours,"
74011,74011,74367,NaN,NaN,NaN,2016-12-05 09:14:09,1978-01-01,0,EL GAREH FATIMA,F,...,14J12,38 ans,NaN,NaN,NaN,EL GAREH,FATIMA,F,1978,
12,12,13,NaN,NaN,NaN,2014-10-31 09:18:33,1994-08-29,0,DOUDRAR FATIMA,F,...,14J13,20 ans,NaN,NaN,NaN,DOUDRAR,FATIMA,F,1994,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252656,252656,253077,NaN,N227862,NaN,2024-11-05 10:03:47,1950-01-01,0,AGERRRIN SADDIA,F,...,24K95,74 ans,NaN,N227862,NaN,AGERRRIN,SADDIA,F,1950,
252657,252657,253078,NaN,N466183,NaN,2024-11-05 10:07:18,1922-02-13,0,AHROUCH YAHYA,M,...,24K96,"2 an(s), 8 mois.",NaN,N466183,NaN,AHROUCH,YAHYA,M,2022,
252660,252660,253081,NaN,NaN,NaN,2024-11-05 10:12:05,1982-01-01,0,AROUB FATNA,F,...,24K97,42 ans,NaN,NaN,NaN,AROUB,FATNA,F,1982,
252667,252667,253088,NaN,N353787,NaN,2024-11-05 10:27:34,1992-03-17,0,DABRAHIM MOHAMMED,M,...,24K98,32 ans,NaN,N353787,NaN,DABRAHIM,MOHAMMED,M,1992,
252669,252669,253090,NaN,NaN,NaN,2024-11-05 10:31:58,1917-01-01,0,IJAOUANE MOHAMED,M,...,24K99,"7 an(s), 10 mois.",NaN,NaN,NaN,IJAOUANE,MOHAMED,M,2017,

difference between data

In [5]:
data_moamuna[['ref' , 'dateheure' , 'cin']][data_moamuna['ref']=='14J49']


#moamuna missed data

Empty DataFrame
Columns: [ref, dateheure, cin]
Index: []

missing names that moamuna dropped and I'll drope too

In [6]:
missing_names ='''15E1568
15I1092
16A1375
16B181
1.60E+278
1.60E+278
16L468
17C171
17C1448
17D5
17G87
17F78
17G312
17G347
17G842
17G1135
17K518
17K1024
18B327
18G332
18G377
18G540
18I722
18K366
19A56
19B662
19G293
20A462
20B259
20F597
21B480
21B370
21G107
18B56
23L71
24A470
'''

missing_names = missing_names.strip().split('\n')
unique_data = unique_data[~unique_data['ref'].isin(missing_names)]
unique_data

,Unnamed: 0,Chun,adresse,region,cin,dateheure,dnaiss,email,nomprenom,ba,...,ref,age,telephone_extracted_from_adresse,cin_from_region,cin_from_adress,nom,prenom,predicted_gender,year_naiss,total_comment
0,0,1,NaN,NaN,NaN,2014-10-31 07:37:46,1958-01-01,0,TRIFHAT RKIA,F,...,14J1,56 ans,NaN,NaN,NaN,TRIFHAT,RKIA,F,1958,"TRAITEMENT ?: SINTROM,"
242396,242396,242815,LA LAGUNE,N398248,N398248,2024-04-24 10:24:04,1995-08-22,0,NADHAMMOU ZINEB,F,...,14J10,28 ans,NaN,N398248,NaN,NADHAMMOU,ZINEB,F,1995,"DDR: ,"
10,10,11,NaN,NaN,NaN,2014-10-31 09:12:00,1973-01-01,0,DAKHISSI MOHAMED,M,...,14J11,41 ans,NaN,NaN,NaN,DAKHISSI,MOHAMED,M,1973,"Abstinence: 3 jours,"
74011,74011,74367,NaN,NaN,NaN,2016-12-05 09:14:09,1978-01-01,0,EL GAREH FATIMA,F,...,14J12,38 ans,NaN,NaN,NaN,EL GAREH,FATIMA,F,1978,
12,12,13,NaN,NaN,NaN,2014-10-31 09:18:33,1994-08-29,0,DOUDRAR FATIMA,F,...,14J13,20 ans,NaN,NaN,NaN,DOUDRAR,FATIMA,F,1994,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252656,252656,253077,NaN,N227862,NaN,2024-11-05 10:03:47,1950-01-01,0,AGERRRIN SADDIA,F,...,24K95,74 ans,NaN,N227862,NaN,AGERRRIN,SADDIA,F,1950,
252657,252657,253078,NaN,N466183,NaN,2024-11-05 10:07:18,1922-02-13,0,AHROUCH YAHYA,M,...,24K96,"2 an(s), 8 mois.",NaN,N466183,NaN,AHROUCH,YAHYA,M,2022,
252660,252660,253081,NaN,NaN,NaN,2024-11-05 10:12:05,1982-01-01,0,AROUB FATNA,F,...,24K97,42 ans,NaN,NaN,NaN,AROUB,FATNA,F,1982,
252667,252667,253088,NaN,N353787,NaN,2024-11-05 10:27:34,1992-03-17,0,DABRAHIM MOHAMMED,M,...,24K98,32 ans,NaN,N353787,NaN,DABRAHIM,MOHAMMED,M,1992,
252669,252669,253090,NaN,NaN,NaN,2024-11-05 10:31:58,1917-01-01,0,IJAOUANE MOHAMED,M,...,24K99,"7 an(s), 10 mois.",NaN,NaN,NaN,IJAOUANE,MOHAMED,M,2017,

In [7]:
difference_in_df1 = unique_data[~ unique_data['ref'].isin(data_moamuna['ref'])]
difference_in_df1[['ref' , 'dateheure', 'nom' , 'prenom','cin']]

          ref            dateheure         nom      prenom  cin
48      14J49  2014-10-31 18:13:17        TEST        ECBU  NaN
13881    15E1  2015-05-01 08:10:31   OUAZZNAHO       AICHA  NaN
13892   15E10  2015-05-01 09:25:50    LAMLAIHI    ESSAADIA  NaN
14051  15E100  2015-05-04 09:58:58     BOUFOUS  ABDELMAJID  NaN
14052  15E101  2015-05-04 10:01:19      KHALDI       SANAA  NaN
...       ...                  ...         ...         ...  ...
13891    15E9  2015-05-01 09:22:39       AARAB      LOUBNA  NaN
14041   15E92  2015-05-04 09:48:03  TAMESSAOUT   ABDELKRIM  NaN
33307   15E93  2015-11-12 11:16:24      FARTAT       NAIMA  NaN
14046   15E95  2015-05-04 09:54:10       DAHBI      FATIMA  NaN
14049   15E98  2015-05-04 09:57:09   OUJAGDARJ     KHADIJA  NaN

[160 rows x 5 columns]

In [8]:
difference_in_df1[difference_in_df1['ref'].isin(data_moamuna['ref'])]

Empty DataFrame
Columns: [Unnamed: 0, Chun, adresse, region, cin, dateheure, dnaiss, email, nomprenom, ba, telephone, sit, observ, comment1, comment2, ref, age, telephone_extracted_from_adresse, cin_from_region, cin_from_adress, nom, prenom, predicted_gender, year_naiss, total_comment]
Index: []

[0 rows x 25 columns]

In [9]:
difference_in_df1.to_excel('Missing_In_Moamuna.xlsx' , index=False)

In [10]:
difference_in_df2 = data_moamuna[~ data_moamuna['ref'].isin(data_moamuna['ref'])]
difference_in_df2

Empty DataFrame
Columns: [Chun, adresse, Unnamed: 2, cin, ref, dateheure, ba, sit, nomprenom, Unnamed: 9, dnaiss, telephone, Unnamed: 12, Unnamed: 13, region, observ, prescri, id, montantsanspreleve, typeprelevement, comment1, comment2, Passeport, Unnamed: 23, Unnamed: 24, Unnamed: 25, Unnamed: 26, Unnamed: 27, Unnamed: 28]
Index: []

[0 rows x 29 columns]

In [11]:
import re
def search_cin(text):
    if isinstance(text, str):
        text = text.replace(' ' , '')
        pattern_with_cin = r'CIN.*([A-Za-z]{1,2}\d{6,7})'
        match = re.search(pattern_with_cin, text, re.IGNORECASE)
        if match:
            return True
        else :
          pattern_without_cin = r'([A-Za-z]{1,2}\d{5,7})'
          match = re.search(pattern_without_cin  , text)
          if match :
            return True
    return False

search_cin('CIN EE242424')

True

In [12]:
cin_moamuna = data_moamuna[['ref' , 'cin']].dropna()[data_moamuna['cin'].apply(search_cin) ]

<ipython-input-12-cc370bdd4c7e>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  cin_moamuna = data_moamuna[['ref' , 'cin']].dropna()[data_moamuna['cin'].apply(search_cin) ]

In [13]:
omar_cin = unique_data[['cin','ref']].dropna()
cin_difference = omar_cin[omar_cin['cin'].isin(cin_moamuna['cin'])]
cin_difference

            cin      ref
170703  N225739    14J29
150828  N217745  14K1053
196672  N328943  14K1060
162742  N137758  14K1095
178455  N257896  14K1107
...         ...      ...
252021  N211395   24A315
245368  N328814   24A398
244922  N126752   24D178
253306   N22444   24E224
250418  N371511   24E305

[3006 rows x 2 columns]

checking data

In [14]:
print("the shape of data is :"  , data_moamuna.shape)
print("after dropping duplicated :" , data_moamuna.drop_duplicates().shape )


difference_in_her_file = data_moamuna[~data_moamuna['ref'].isin(unique_data['ref'])]
difference_in_her_file.to_excel("Missing_In_mine.xlsx")

the shape of data is : (104139, 29)
after dropping duplicated : (104139, 29)

In [15]:
unique_data['cin'].isna().sum()
ref_cin_missing = data_moamuna[~data_moamuna['cin'].isin(unique_data['cin'])]['ref']
unique_data[unique_data['ref'].isin(ref_cin_missing)]

,Unnamed: 0,Chun,adresse,region,cin,dateheure,dnaiss,email,nomprenom,ba,...,ref,age,telephone_extracted_from_adresse,cin_from_region,cin_from_adress,nom,prenom,predicted_gender,year_naiss,total_comment
94933,94933,95323,NaN,NaN,NaN,2017-05-25 10:16:15,1967-01-01,0,SABIR KHADIJA,F,...,14J27,50 ans,NaN,NaN,N173047,SABIR,KHADIJA,F,1967,
170703,170703,171106,209 lot 5,N225739,N225739,2019-10-29 10:07:32,1982-01-08,0,ID SAID MINA,F,...,14J29,37 ans,NaN,N225739,NaN,ID,MINA,F,1982,
217175,217175,217582,CARTE PATIENT,BJ167528,BJ167528,2021-09-22 10:59:08,1974-01-01,0,LOUAFI LAKBIRA,F,...,14J43,47 ans,NaN,BJ167528,NaN,LOUAFI,LAKBIRA,F,1974,
218946,218946,219355,LOT 5,NaN,NaN,2021-10-14 10:03:03,1988-04-30,0,EL BARDADI KHADIJA,F,...,14J9,33 ans,NaN,NaN,NaN,EL BARDADI,KHADIJA,F,1988,
170502,170502,170905,NaN,NaN,NaN,2019-10-26 09:52:20,1965-04-28,0,TIZZA WAFAA,F,...,14K101,54 ans,NaN,NaN,NaN,TIZZA,WAFAA,F,1965,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252521,252521,252942,LA LAGUNE,N114174,NaN,2024-11-04 09:12:35,1964-01-01,0,AKHALLOUF FATIMA,F,...,24K38,60 ans,NaN,N114174,NaN,AKHALLOUF,FATIMA,F,1964,
252526,252526,252947,FILS MAHRAZ MED,NaN,NaN,2024-11-04 09:27:15,1967-01-01,0,KARIM ESSAADIA,F,...,24K40,57 ans,NaN,NaN,NaN,KARIM,ESSAADIA,F,1967,
252599,252599,253020,LOT5,N415821,NaN,2024-11-04 17:08:31,1996-01-09,0,TOUBALI ABDELHAKIM,M,...,24K72,28 ans,NaN,N415821,NaN,TOUBALI,ABDELHAKIM,M,1996,"Abstinence: ,"
252640,252640,253060,fille khadija el aloui maternite,NaN,NaN,2024-11-05 09:25:12,1960-02-22,0,TIBIBICHE NAIMA,F,...,24K82,64 ans,NaN,NaN,NaN,TIBIBICHE,NAIMA,F,1960,
252646,252646,253067,fils,NaN,NaN,2024-11-05 09:44:17,1964-01-01,0,JAA AICHA,F,...,24K88,60 ans,NaN,NaN,NaN,JAA,AICHA,F,1964,

In [16]:
import re
import numpy as np
def format_phone(text):
  text = str(text)
  pattern = r'(\d{9})\.(\d{1})'
  match = re.search(pattern , text)

  if match :
    return f'{match.group(2)}{match.group(1)}'
  return text

data['telephone'] = data['telephone'].apply(format_phone)

In [17]:
non_cin = data['cin'].dropna().apply(search_cin)
data['cin'].iloc[non_cin[~non_cin].index] = data['cin'].iloc[non_cin[~non_cin].index ].apply(lambda x : np.nan)

data['cin'].dropna()

<ipython-input-17-37627093b076>:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['cin'].iloc[non_cin[~non_cin].index] = data['cin'].iloc[non_cin[~non_cin].index ].apply(lambda x : np.nan)
<ipython-input-17-37627093b076>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['cin'].iloc[non_cin[~non_cin].index] = data['cin'].iloc[non_cin[~non_cin].index ].apply(lambda x : np.nan)

1         J485388
2         N105701
9         N398248
14         N51316
18        N196554
           ...
253544     N30474
253547     N94479
253550     N31077
253559    N226101
253564    J282843
Name: cin, Length: 75831, dtype: object

In [18]:
data['cin'].dropna().apply(search_cin).value_counts()

cin
True    75831
Name: count, dtype: int64

fix phone

In [19]:
def search_phone(text):
  text = str(text)
  text = text.upper().replace(' ' , '')
  pattern_phone = r'\d{10}'

  match = re.search(pattern_phone , text)
  if match :
    return True
  return False

search_phone('HH0710101010HH')


non_phone = data['telephone'].apply(search_phone)
non_phone_index = non_phone[~ non_phone].index

data['telephone'].iloc[non_phone_index] = data['telephone'].iloc[non_phone_index].apply(lambda x : np.nan  )

data['telephone'].dropna().apply(search_phone).value_counts()

<ipython-input-19-f8e1eed32526>:17: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['telephone'].iloc[non_phone_index] = data['telephone'].iloc[non_phone_index].apply(lambda x : np.nan  )
<ipython-input-19-f8e1eed32526>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['telephone'].iloc[non_phone_index] = data['telephone'].iloc[non_phone_index].apply(lambda x : np.nan  )

telephone
True    160023
Name: count, dtype: int64

missing patients ?

In [20]:
data.to_csv("data_patient_cleaned.csv")

In [21]:
export_patient = pd.read_excel('/content/export_patients.xlsx' )

replacing cin with logic

In [22]:
def search_cin(text):
    if isinstance(text, str):
        text = text.replace(' ' , '').upper()
        pattern_with_cin = r'CIN.*([A-Za-z]{1,2}\d{6,7})'
        match = re.search(pattern_with_cin, text, re.IGNORECASE)
        if match:
            return True
        else :
          pattern_without_cin = r'([A-Za-z]{1,2}\d{5,7})'
          match = re.search(pattern_without_cin  , text)
          if match :
            return True
    return False


def extract_cin(text):
    text = str(text).upper().replace(' ', '')

    # Patterns that require "CIN" prefix followed by valid code (letters+digits)
    patterns_with_cin = [
        r'CIN[:.\s]*([A-Z]{2}\d{6})',
        r'CIN[:.\s]*([A-Z]{2}\d{5})',
        r'CIN[:.\s]*([A-Z]{1}\d{7})',
        r'CIN[:.\s]*([A-Z]{1}\d{6})',
        r'CIN[:.\s]*([A-Z]{1}\d{5})'
    ]

    # Patterns without CIN prefix
    patterns_without_cin = [
        r'([A-Z]{2}\d{6})',
        r'([A-Z]{2}\d{5})',
        r'([A-Z]{1}\d{7})',
        r'([A-Z]{1}\d{6})',
        r'([A-Z]{1}\d{5})'
    ]

    #  match with CIN prefix first
    for pattern in patterns_with_cin:
        match = re.search(pattern, text)
        if match:
            return match.group(1)

    # Then  match without CIN prefix
    for pattern in patterns_without_cin:
        match = re.search(pattern, text)
        if match:
            return match.group(1)

    return np.nan

# Testing
print(extract_cin('68LOT AZELF ESSAOUIRA CIN:N13458'))

N13458

In [23]:
data_columns = export_patient.columns.tolist()
cin_columns = []
new_cin_column = []
for column in data_columns :
  column_selected = export_patient[column].dropna()[export_patient[column].apply(search_cin)]
  size = column_selected.shape[0]
  if size > 20 :

    cin_columns.append(column)
    name_column = f'cin_from_{column}'
    new_cin_column.append(name_column)
    export_patient[name_column] = column_selected.apply(extract_cin)

In [24]:
new_cin_column

['cin_from_cin', 'cin_from_adresse', 'cin_from_region', 'cin_from_observ']

In [25]:
export_patient['cin_from_adresse'].dropna()

26        N173047
176        N39561
280       N338845
313       N114587
329        N16067
           ...
253519    N143714
253522     B93318
253532    N284419
253555    N316168
253560    N358582
Name: cin_from_adresse, Length: 37513, dtype: object

In [26]:
filled = export_patient['adresse'].dropna()[export_patient['adresse'].apply(search_cin)].apply(extract_cin).isna()
filled  = filled[filled]
filled_index = filled.index
export_patient['adresse'].iloc[filled_index]

Series([], Name: adresse, dtype: object)

extracted all cin seccusefully

In [27]:
true_cin = export_patient['cin'].dropna().apply(search_cin)
true_cin_index = true_cin[~true_cin].index

export_patient['cin'].iloc[true_cin_index]

239898    PAS 22FH8736
240077           N9546
240281    CIN : N 1052
240291           N8115
240336           N1039
240530      0649082081
242525    PERE A.LATIF
243542           N2320
243550     tahelounate
243945               0
244303    PASS 15DC493
244804               0
245644           N2320
247576      COMMISAIRE
248305        3 COPIES
250420             062
250511               0
251898      FILS MOUAD
Name: cin, dtype: object

In [28]:
export_patient['cin'].iloc[true_cin_index] = export_patient['cin'].iloc[true_cin_index].apply(lambda x : np.nan)
export_patient['cin'].iloc[true_cin_index]

<ipython-input-28-b4467047ae06>:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  export_patient['cin'].iloc[true_cin_index] = export_patient['cin'].iloc[true_cin_index].apply(lambda x : np.nan)
<ipython-input-28-b4467047ae06>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  export_patient['cin'].iloc[true_cin_index] = export_patient['cin'].iloc[true_cin_index].apply(lambda x : np.nan)

239898    NaN
240077    NaN
240281    NaN
240291    NaN
240336    NaN
240530    NaN
242525    NaN
243542    NaN
243550    NaN
243945    NaN
244303    NaN
244804    NaN
245644    NaN
247576    NaN
248305    NaN
250420    NaN
250511    NaN
251898    NaN
Name: cin, dtype: object

In [29]:
export_patient['cin_from_cin'].dropna()

198614    EE468260
228250      N23745
234656     N399946
240003     N002999
240263      N51220
            ...
248096     N002238
248298     N145954
248393     H212394
249345    IN676522
251562      N34683
Name: cin_from_cin, Length: 71, dtype: object

apply idea

In [30]:
for column_replace in new_cin_column :
  data_replace = export_patient[column_replace]
  mask = export_patient['cin'].isna() & export_patient[column_replace].notna()
  export_patient.loc[mask , 'cin'] = data_replace[mask]
  # replace if data['cin'] null  at the same index

83276 rows √ó 1 columns now

In [31]:
export_patient['cin'].dropna()

14         N51316
26        N173047
68         N68584
176        N39561
245        N77590
           ...
253548     N20375
253554    N188590
253555    N316168
253560    N358582
253561     N26867
Name: cin, Length: 83276, dtype: object

replace rest of null with mode because we have frequent patients with more than visit

In [32]:
visit_counts = export_patient['ref'].value_counts()

# Filter patients with at least 2 visits
patients_with_2plus = visit_counts[visit_counts >= 2].index

# Now filter your dataframe to keep only those patients
filtered_df = export_patient[export_patient['ref'].isin(patients_with_2plus)][['ref', 'cin']].sort_values('ref')

filtered_df

          ref      cin
197502  14J10  N398248
200850  14J10  N398248
242396  14J10  N398248
186570  14J10  N398248
238871  14J10  N398248
...       ...      ...
252639  24K75  N171230
252644  24K86  N426270
253449  24K86      NaN
252648  24K90  UA23496
253042  24K90      NaN

[189341 rows x 2 columns]

In [33]:
visit_counts = export_patient['ref'].value_counts()

# Filter patients with at least 2 visits
patients_with_2plus = visit_counts[visit_counts >= 2].index

# Now filter your dataframe to keep only those patients
filtered_df = export_patient[export_patient['ref'].isin(patients_with_2plus)][['ref', 'cin']].sort_values('ref')

filtered_df

modes_phones = export_patient.groupby('ref')['cin'].agg(
    lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan
)


modes_phones_dict = modes_phones.to_dict()

def fill_phone(row):
  return modes_phones_dict.get(row['ref'] , np.nan)

In [34]:

filtered_df['cin'] = filtered_df.apply(fill_phone , axis=1)
filtered_df[filtered_df['ref']=='24K75']

          ref      cin
252607  24K75  N171230
252639  24K75  N171230

In [35]:
export_patient['mode_cin'] = filtered_df['cin']

In [36]:
mask = export_patient['cin'].isna() & export_patient['mode_cin'].notna()
export_patient[export_patient['cin'].isna() & export_patient['mode_cin'].notna() ][['cin' , 'mode_cin']]

        cin mode_cin
1       NaN  J485388
2       NaN  N105701
9       NaN  N398248
18      NaN  N196554
20      NaN  GM55243
...     ...      ...
253547  NaN   N94479
253549  NaN  N390772
253550  NaN   N31077
253559  NaN  N226101
253564  NaN  J282843

[52285 rows x 2 columns]

In [37]:
export_patient.loc[mask , 'cin'] = export_patient.loc[mask  , 'mode_cin']

In [38]:
export_patient['cin']

0             NaN
1         J485388
2         N105701
3             NaN
4             NaN
           ...
253560    N358582
253561     N26867
253562        NaN
253563        NaN
253564    J282843
Name: cin, Length: 253565, dtype: object

In [39]:
data['cin'] = export_patient['cin']

In [40]:
print(f"the shape of data_moamuna{data_moamuna.shape} , the shape of omar_data{unique_data.shape}" )
print(f"number of valid cin of moamuna {data_moamuna['cin'].dropna().shape[0] - 4155}")
print(f"number of valid cin of moamuna {unique_data['cin'].dropna().shape[0]}")

the shape of data_moamuna(104139, 29) , the shape of omar_data(103651, 25)
number of valid cin of moamuna 16654
number of valid cin of moamuna 14206

In [41]:
not_cin_moamuna = data_moamuna['cin'].dropna().apply(search_cin)
not_cin_moamuna = not_cin_moamuna[~not_cin_moamuna].index
data_moamuna['cin'].iloc[not_cin_moamuna]

0                           cin
93                         3520
313                       UD932
2054                      N4818
3960               soeur hassna
                  ...
103820                tel tarri
103840    MARI:   ZAGUIR MILOUD
103861     bab doukala/ass SIDA
103868                FILS ARAF
103972                608 azlef
Name: cin, Length: 4155, dtype: object

In [42]:
data_moamuna['region'].apply(search_cin).value_counts()

region
False    104139
Name: count, dtype: int64

extracting phone from all column

In [43]:
def search_fax(text):
  if isinstance(text , str):
    text = text.replace(' ' , '')
    patterns_phone =r'\D'
    filtered = re.sub(patterns_phone,'' , text)
    extract_fax = re.search(r'(\d{9})' , filtered)
    if extract_fax :
      return True
  return False


def extract_fax(text):
  if isinstance(text , str):
    text = text.replace(' ' , '')
    patterns_phone =r'\D'
    filtered = re.sub(patterns_phone,'' , text)
    pattern_fax1 = re.search(r'(?:212)*[+*.:/,-]*(0\d{9})$' , filtered)
    pattern_fax2 = re.search(r'(?:212)*[+*.:/,-]*(\d{9})$' , filtered)

    if pattern_fax1 :
      return pattern_fax1.group(1)

    elif pattern_fax2 :
      return '0' + pattern_fax2.group(1)

  return np.nan
print(extract_fax('CIN : N 159477 / 670249049'))
print(extract_fax('CIN : N 159477 / 212+0670249049'))

0670249049
0670249049

In [44]:
print(export_patient['telephone'].isna().sum())

data_columns = export_patient.columns.tolist()
phone_columns = []
new_phone_column = []
for column in data_columns :
  column_selected = export_patient[column].dropna().apply(extract_fax)
  size = column_selected.shape[0]
  if size > 20 :

    cin_columns.append(column)
    name_column = f'phone_from_{column}'
    new_cin_column.append(name_column)
    export_patient[name_column] = column_selected

41715

In [45]:
for column_replace in new_cin_column :
  data_replace = export_patient[column_replace]
  mask = export_patient['telephone'].isna() & export_patient[column_replace].notna()
  export_patient.loc[mask , 'telephone'] = data_replace[mask]
  # replace if data['cin'] null  at the same index

In [46]:
export_patient['telephone'][~export_patient['telephone'].apply(search_fax)].dropna()

68          N68584
176         N39561
449        N164308
620             06
659       26111955
            ...
253500      N47892
253504     N123528
253518           *
253540     N500882
253542     N239161
Name: telephone, Length: 12364, dtype: object

replacing with mode

In [47]:
# Now filter your dataframe to keep only those patients, including the 'telephone' column
filtered_df = export_patient[export_patient['ref'].isin(patients_with_2plus)][['ref', 'cin', 'telephone']].sort_values('ref')

modes_phones = export_patient.groupby('ref')['telephone'].agg(
    lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan
)

modes_phones_dict = modes_phones.to_dict()

def fill_phone(row):
  # Use the modes_phones_dict to get the mode telephone for the patient's ref
  return modes_phones_dict.get(row['ref'] , np.nan)


filtered_df['telephone'] = filtered_df.apply(fill_phone , axis=1)

export_patient['mode_telephone'] = filtered_df['telephone']

# Correct the mask logic and the assignment
mask = export_patient['cin'].isna() & export_patient['mode_cin'].notna()
export_patient.loc[mask , 'cin'] = export_patient.loc[mask  , 'mode_cin']

# Correct the mask logic and the assignment for telephone
mask_tel = export_patient['telephone'].isna() & export_patient['mode_telephone'].notna()
export_patient.loc[mask_tel , 'telephone'] = export_patient.loc[mask_tel  , 'mode_telephone']

export_patient['telephone']

0         0661425650
1         0607098707
2         0666014056
3         0666594273
4         0666155610
             ...
253560    0699334313
253561    0610904616
253562    0648816169
253563    0610088262
253564    0677787961
Name: telephone, Length: 253565, dtype: object

In [48]:
false_number = export_patient['telephone'].apply(lambda x : np.nan if x =='nan' else x ).dropna().apply(search_fax)
false_number_index = false_number[~ false_number].index
export_patient['telephone'].iloc[false_number_index] = export_patient['telephone'].iloc[false_number_index].apply(lambda x : np.nan)

<ipython-input-48-b729e0a47cc5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  export_patient['telephone'].iloc[false_number_index] = export_patient['telephone'].iloc[false_number_index].apply(lambda x : np.nan)

In [49]:
export_patient['telephone'].isna().sum()

np.int64(36934)

telephone is much less now

In [50]:
data['telephone'] = export_patient['telephone']

In [51]:
data_sorted  = data.sort_values(by=['ref','dateheure'] , ascending=[True , False] )
unique_data = data_sorted.drop_duplicates(subset='ref' , keep='first')

In [52]:
data.to_excel('all_data_patient_final_clean.xlsx' , index=False)
unique_data.to_excel('unique_data_patient.xlsx' , index=False)

In [56]:
unique_data['telephone'].dtype

dtype('O')