In [736]:
import pandas as pd



data_patient = pd.read_excel("/content/export_patients.xlsx")

devising the file because it's to large and will slow the memory

In [737]:
'''import math

division = 4
number_samples = len(data_patient)
slicing  = math.ceil( number_samples / division)

init = 0




for i in range(division):
  start = i*slicing
  end = start + slicing
  data_part  = data_patient.iloc[start:end]
  name_file = f"data_patient{i+1}.xlsx"
  data_part.to_excel(name_file , index=False)'''

'import math\n\ndivision = 4\nnumber_samples = len(data_patient)\nslicing  = math.ceil( number_samples / division)\n\ninit = 0 \n\n\n\n\nfor i in range(division):\n  start = i*slicing \n  end = start + slicing \n  data_part  = data_patient.iloc[start:end]\n  name_file = f"data_patient{i+1}.xlsx"\n  data_part.to_excel(name_file , index=False)'

In [738]:
'''data_patient = pd.read_excel("/content/data_patient.xlsx")'''

'data_patient = pd.read_excel("/content/data_patient.xlsx")'

In [739]:
data_patient.columns

Index(['ref', 'datevisite', 'dateheure', 'Heure', 'ba', 'sit', 'nomprenom',
       'cin', 'dnaiss', 'age', 'agejours', 'telephone', 'adresse', 'region',
       'observ', 'prescri', 'modalite', 'clinique', 'chambre', 'retrait1',
       'retrait1conv', 'retrait2', 'retrait2conv', 'heureretrait',
       'heureretrait2', 'recupere', 'daterecupere', 'convdaterecupere',
       'montantsanspreleve', 'typeprelevement', 'heure_preleve', 'nom_preleve',
       'prelevement', 'montantfinal', 'remise', 'montantfinalremise',
       'convdate', 'reelsanspreleve', 'prixreel', 'Chun', 'cotb',
       'RefAutomate', 'mutuelle', 'sav', 'mtsel', 'comment1', 'comment2',
       'Ch1', 'Num1', 'Imp_Retrait', 'Imp_Facture', 'valide', 'urgent',
       'ordreimp', 'email'],
      dtype='object')

In [740]:
columns_we_need  = ['Chun' , 'adresse' , 'region' , 'cin' ,
                    'dateheure' ,'dnaiss' , 'email' , 'nomprenom' ,
                    'ba' , 'telephone' ,'sit','observ' , 'comment1' ,'comment2' ,
                    'ref' , 'age'
                    ]


data_patient = data_patient[columns_we_need]

In [741]:
import re

column email

In [742]:
data_patient['email'].value_counts()[0].tolist()


valid_email_pattern = r'[\w\.-]+@[\w\.-]+\.\w+'
data_patient['adresse'][data_patient['adresse'].str.contains(valid_email_pattern , na=False)]
#email doesn't exists in the data patient 1

data_patient['email'].value_counts()[0] ,  data_patient['email'].shape[0]

data_patient['email'][~data_patient['email'].isin([0,1]) ]
#  only [0 , 1 ] that contain this column

Series([], Name: email, dtype: int64)

column  adresse

In [743]:
data_patient['adresse'][data_patient['adresse'].notna()]
#this column adresse  have the Cin|fax|adresse of the patient



#data_patient['adresse'][data_patient['adresse'].str.match(r'\d+' , na=False)]


#extracting cin from the column


def search_cin(text):
    if isinstance(text, str):
        text = text.replace(' ' , '')
        pattern_with_cin = r'CIN.*([A-Za-z]{1,2}\d{6,7})'
        match = re.search(pattern_with_cin, text, re.IGNORECASE)
        if match:
            return True
        else :
          pattern_without_cin = r'([A-Za-z]{1,2}\d{5,7})'
          match = re.search(pattern_without_cin  , text)
          if match :
            return True
    return False



data_patient['adresse'][data_patient['adresse'].apply(search_cin)]

#we have 983 Cin in the column adresse

26               CIN : N 173047
176               CIN : N 39561
280                     N338845
313                     N114587
329                  CIN:N16067
                  ...
253519    CIN: N143714  TAFEDNA
253522          B93318    AZLEF
253532             CIN: N284419
253555             CIN: N316168
253560           CIN : N 358582
Name: adresse, Length: 37513, dtype: object

In [744]:
data_patient['cin'].dropna()

198614        EE468260
228250          N23745
234656         N399946
239898    PAS 22FH8736
240003        N002999P
              ...
249345    CIN 6765228Q
250420             062
250511               0
251562         N34683
251898      FILS MOUAD
Name: cin, Length: 89, dtype: object

extracting_cin

In [745]:
def extract_cin(text):
    if isinstance(text, str):
        text = text.upper()
        text = text.replace(' ' , '')
        pattern_with_cin = r'CIN.*([A-Za-z]{1,2}\d{5,7})'
        match = re.search(pattern_with_cin, text, re.IGNORECASE)
        if match:
            return match.group(1)
        else :
          pattern_without_cin = r'([A-Za-z]{1,2}\d{6,7})'
          match = re.search(pattern_without_cin  , text , re.IGNORECASE)
          if match :
            return match.group(1)
    return False

def extract_cin(cin):
  cin = cin.upper()
  cin = cin.replace(" ", '')
  pattern= r'([A-Z]{1,2}\d{5,7})'
  match = re.search(pattern , cin)
  if match :
    return match.group(1)
  return 'False'




cin = data_patient['adresse'][data_patient['adresse'].apply(search_cin)].apply(extract_cin)
cin

26        N173047
176        N39561
280       N338845
313       N114587
329        N16067
           ...
253519    N143714
253522     B93318
253532    N284419
253555    N316168
253560    N358582
Name: adresse, Length: 37513, dtype: object

In [746]:
def extract_cin(text):
  text = str(text)
  text = text.replace(' ' , '')
  text = text.upper()
  patter1_cin = r'([A-Z]{2}\d{6})'
  pattern2_cin = r'([A-Z]{1}\d{7})'
  pattern3_cin = r'([A-Z]{1}\d{6})'
  pattern4_cin = r'([A-Z]{1}\d{5})'



  for pattern in [patter1_cin , pattern2_cin , pattern3_cin]:
    match = re.search(pattern , text)
    if match :
      return match.group(1)
  return False





extract_cin('CIN : NN 173047555')


cin = data_patient['adresse'][data_patient['adresse'].apply(search_cin)].apply(extract_cin)
cin

26        N173047
176         False
280       N338845
313       N114587
329         False
           ...
253519    N143714
253522      False
253532    N284419
253555    N316168
253560    N358582
Name: adresse, Length: 37513, dtype: object

extract phone number

extract fax from adresse

In [747]:
from ast import pattern
def search_fax(text):
  if isinstance(text , str):
    text = text.replace(' ' , '')
    patterns_phone =r'\D'
    filtered = re.sub(patterns_phone,'' , text)
    extract_fax = re.match(r'\d{10}' , filtered)
    if extract_fax :
      return True
  return False



#data_patient['adresse'][data_patient['adresse'].apply(search_fax)]

In [748]:
from ast import pattern
def search_fax(text):
  if isinstance(text , str):
    text = text.replace(' ' , '')
    patterns_phone =r'\D'
    filtered = re.sub(patterns_phone,'' , text)
    extract_fax = re.search(r'(0\d{9})' , filtered)
    if extract_fax :
      return True
  return False


def extract_fax(text):
  if isinstance(text , str):
    text = text.replace(' ' , '')
    patterns_phone =r'\D'
    filtered = re.sub(patterns_phone,'' , text)
    extract_fax = re.search(r'(0\d{9})' , filtered)
    if extract_fax :
      return extract_fax.group(1)
  return False
search_fax('CIN : N 159477 / 0670249049')




data_patient['adresse'][ data_patient['adresse'].apply(search_fax)]

584                            0662858263
1673            CIN : N 164164/0611076737
1924                           0696243073
4107                           0690252805
4849          CIN : N 159477 / 0670249049
                       ...
253070    CIN: N257510 takate /0622274942
253106                par tel  0638972795
253130         N48590/0678574042 SA FEMME
253289                         0684303206
253549                         0627348404
Name: adresse, Length: 2943, dtype: object

extract fax from adresse and replacing the column

In [749]:
telephone_extracted_from_adresse = data_patient['adresse'][ data_patient['adresse'].apply(search_fax)].apply(extract_fax)
telephone_extracted_from_adresse.name = 'telephone_extracted_from_adresse'
telephone_extracted_from_adresse

data_patient['telephone_extracted_from_adresse'] =  telephone_extracted_from_adresse

In [750]:
data_patient[['telephone_extracted_from_adresse' , 'telephone']].dropna()[data_patient['telephone_extracted_from_adresse'] == data_patient['telephone']]

<ipython-input-750-ad6878a7b819>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data_patient[['telephone_extracted_from_adresse' , 'telephone']].dropna()[data_patient['telephone_extracted_from_adresse'] == data_patient['telephone']]

       telephone_extracted_from_adresse   telephone
14849                        0642846505  0642846505
15428                        0672510307  0672510307
36166                        0666234631  0666234631
66472                        0672510307  0672510307
68298                        0661657390  0661657390
...                                 ...         ...
243856                       0707122133  0707122133
244176                       0693775343  0693775343
249536                       0693775343  0693775343
250830                       0666234631  0666234631
252882                       0707122133  0707122133

[87 rows x 2 columns]

extract adresse from adresse

In [751]:
import numpy as np
data_patient[data_patient['telephone'].isna() ]['telephone']



missing_phone  =data_patient[~data_patient['telephone'].astype(str).str.match(r'\d+' ) ]['telephone'].dropna()
data_patient.loc[missing_phone.index, 'telephone'] = np.nan

In [752]:
#replaced noses phone with np.nan (Null)
data_patient['telephone'].dropna()

0         0661425650
1         0607098707
2         0666014056
3         0666594273
4         0666155610
             ...
253560    0699334313
253561    0610904616
253562    0648816169
253563    0610088262
253564    0677787961
Name: telephone, Length: 210902, dtype: object

using the data from other visits to fill missing phones is a good idea to clean data

In [753]:
freq_df = data_patient['ref'].value_counts().reset_index()
freq_df.columns = ['patient_id', 'visit_count']
freq_df.sort_values('patient_id')

       patient_id  visit_count
103684       14J1            1
5579        14J10            8
103680      14J11            1
15465       14J12            4
103679      14J13            1
...           ...          ...
103367      24K95            1
103366      24K96            1
103365      24K97            1
103396      24K98            1
103395      24K99            1

[103685 rows x 2 columns]

In [754]:
data_patient.head()

,Chun,adresse,region,cin,dateheure,dnaiss,email,nomprenom,ba,telephone,sit,observ,comment1,comment2,ref,age,telephone_extracted_from_adresse
0,1,NaN,NaN,NaN,2014-10-31 07:37:46,01/01/1958,0,TRIFHAT RKIA,FÃ©minin,0661425650,MME,"TRAITEMENT ?: SINTROM,",NaN,NaN,14J1,56 ans,NaN
1,2,NaN,NaN,NaN,2014-10-31 07:49:36,04/01/1993,0,CHBIKI SALIMA,FÃ©minin,0607098707,MME,"Grossesse ?: OUI,",NaN,NaN,14J2,21 ans,NaN
2,3,NaN,NaN,NaN,2014-10-31 07:58:42,01/01/1960,0,NAIMI FATIMA,FÃ©minin,0666014056,MME,NaN,NaN,NaN,14J3,54 ans,NaN
3,4,NaN,NaN,NaN,2014-10-31 08:03:07,12/12/1961,0,GHASSOUL ZOHRA,FÃ©minin,0666594273,MME,NaN,NaN,NaN,14J4,52 ans,NaN
4,5,NaN,NaN,NaN,2014-10-31 08:06:34,30/04/1962,0,EL KHARRIGO TAOUFIQ,FÃ©minin,0666155610,MME,NaN,NaN,NaN,14J5,54 ans,NaN

In [755]:
data_patient[['ref' , 'cin' , 'telephone']].sort_values('ref')

          ref  cin   telephone
0        14J1  NaN  0661425650
203594  14J10  NaN  0633751454
200850  14J10  NaN  0633751454
242396  14J10  NaN  0633751454
9       14J10  NaN  0633751454
...       ...  ...         ...
252656  24K95  NaN         NaN
252657  24K96  NaN  0699604312
252660  24K97  NaN         NaN
252667  24K98  NaN  0651837868
252669  24K99  NaN  0644251276

[253565 rows x 3 columns]

patients with more than two visits

In [756]:
visit_counts = data_patient['ref'].value_counts()

# Filter patients with at least 2 visits
patients_with_2plus = visit_counts[visit_counts >= 2].index

# Now filter your dataframe to keep only those patients
filtered_df = data_patient[data_patient['ref'].isin(patients_with_2plus)][['ref', 'cin', 'telephone']].sort_values('ref')

filtered_df

          ref  cin   telephone
197502  14J10  NaN  0633751454
200850  14J10  NaN  0633751454
242396  14J10  NaN  0633751454
186570  14J10  NaN  0633751454
238871  14J10  NaN  0633751454
...       ...  ...         ...
252639  24K75  NaN         NaN
252644  24K86  NaN  0676331448
253449  24K86  NaN  0676331448
252648  24K90  NaN  0670893811
253042  24K90  NaN  0670893811

[189341 rows x 3 columns]

In [757]:
data_patient['telephone'] = filtered_df['telephone']
data_patient['telephone']

0                NaN
1         0607098707
2         0666014056
3                NaN
4         0666155610
             ...
253560    0699334313
253561           NaN
253562    0648816169
253563           NaN
253564    0677787961
Name: telephone, Length: 253565, dtype: object

In [758]:
modes_phones = data_patient.groupby('ref')['telephone'].agg(
    lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan
)


modes_phones_dict = modes_phones.to_dict()

def fill_phone(row):
  return modes_phones_dict.get(row['ref'] , np.nan)

In [759]:

filtered_df['telephone'] = filtered_df.apply(fill_phone , axis=1)
filtered_df[filtered_df['ref']=='24K75']

          ref  cin telephone
252607  24K75  NaN       NaN
252639  24K75  NaN       NaN

In [760]:
modes_phones

ref
14J1            NaN
14J10    0633751454
14J11           NaN
14J12    0618050590
14J13           NaN
            ...
24K95           NaN
24K96           NaN
24K97           NaN
24K98           NaN
24K99           NaN
Name: telephone, Length: 103685, dtype: object

In [761]:
data_patient[['telephone_extracted_from_adresse' , 'telephone']][ data_patient['telephone'].isna() & data_patient['telephone_extracted_from_adresse'].notna()]

       telephone_extracted_from_adresse telephone
35602                        0627716805       NaN
36024                        0639151587       NaN
57694                        0662037118       NaN
66625                        0676245753       NaN
74038                        0677543387       NaN
...                                 ...       ...
248724                       0023680714       NaN
250555                       0616430890       NaN
251213                       0524792682       NaN
252059                       0644809333       NaN
252296                       0636774162       NaN

[144 rows x 2 columns]

In [762]:
mask = data_patient['telephone'].isna() & data_patient['telephone_extracted_from_adresse'].notna()
data_patient.loc[mask, 'telephone'] = data_patient.loc[mask, 'telephone_extracted_from_adresse']
#verification
data_patient[['telephone' , 'telephone_extracted_from_adresse' ]].iloc[36024]

telephone                           0639151587
telephone_extracted_from_adresse    0639151587
Name: 36024, dtype: object

extract cin from region

In [763]:
data_patient['cin'].isna().sum()

np.int64(253476)

In [764]:
def extract_cin(text):
  text = str(text)
  text = text.replace(' ' , '')
  text = text.upper()
  patter1_cin = r'([A-Z]{2}\d{6})'
  pattern2_cin = r'([A-Z]{1}\d{7})'
  pattern3_cin = r'([A-Z]{1}\d{6})'
  pattern4_cin = r'([A-Z]{1}\d{5})'



  for pattern in [patter1_cin , pattern2_cin , pattern3_cin, pattern4_cin]:
    match = re.search(pattern , text)
    if match :
      return match.group(1)
  return np.nan


extract_cin('N51316')

'N51316'

In [765]:
# extract cin from region

cin_index = data_patient['region'].dropna().apply(search_cin)
cin_index = cin_index[cin_index].index
cin_from_region = data_patient['region'].iloc[cin_index].apply(extract_cin)

data_patient['cin_from_region'] = cin_from_region

data_patient['cin'] = data_patient[['cin_from_region','cin']].dropna(subset=['cin_from_region'] , how='any')['cin_from_region']

data_patient['cin'].dropna()

14         N51316
68         N68584
245        N77590
449       N164308
453       N285910
           ...
253540    N500882
253542    N239161
253548     N20375
253554    N188590
253561     N26867
Name: cin, Length: 45758, dtype: object

In [766]:
data_patient[['cin' , 'cin_from_region']]

           cin cin_from_region
0          NaN             NaN
1          NaN             NaN
2          NaN             NaN
3          NaN             NaN
4          NaN             NaN
...        ...             ...
253560     NaN             NaN
253561  N26867          N26867
253562     NaN             NaN
253563     NaN             NaN
253564     NaN             NaN

[253565 rows x 2 columns]

In [767]:
data_patient['cin'] =  data_patient['cin'].dropna().apply(extract_cin)

replacing CIN

In [768]:
extract_cin_from_cin = data_patient['cin'].dropna().apply(extract_cin)
data_patient['cin']= extract_cin_from_cin[extract_cin_from_cin !=False]
data_patient['cin_from_adress'] = cin


data_patient[['cin' , 'cin_from_adress']].dropna()

            cin cin_from_adress
75038   N223236         N223236
103963  N307894         N307894
118696  N163016           False
119126  N205118         N205118
119183   N74585           False
...         ...             ...
242579   N76816        NE706111
243116  N299550         N299550
243366  N257398         N257398
251792  N299550         N299550
252266  N255622         N255622

[212 rows x 2 columns]

replace cin_from_adresse to cin

In [769]:
mask = data_patient['cin'].isna() & data_patient['cin_from_adress'].notna()
data_patient.loc[mask, 'cin'] = data_patient.loc[mask, 'cin_from_adress']


data_patient['cin'].dropna()

14         N51316
26        N173047
68         N68584
176         False
245        N77590
           ...
253548     N20375
253554    N188590
253555    N316168
253560    N358582
253561     N26867
Name: cin, Length: 83059, dtype: object

now felling the messing column with the mode because some patients are frequent

In [770]:
visit_counts = data_patient['ref'].value_counts()

# Filter patients with at least 2 visits
patients_with_2plus = visit_counts[visit_counts >= 2].index

# Now filter your dataframe to keep only those patients
filtered_df = data_patient[data_patient['ref'].isin(patients_with_2plus)][['ref', 'cin']].sort_values('ref')

filtered_df

          ref      cin
197502  14J10  N398248
200850  14J10  N398248
242396  14J10  N398248
186570  14J10  N398248
238871  14J10  N398248
...       ...      ...
252639  24K75  N171230
252644  24K86  N426270
253449  24K86      NaN
252648  24K90   A23496
253042  24K90      NaN

[189341 rows x 2 columns]

In [771]:
# Step 1: For each patient, check if there is at least one non-null CIN
has_cin = filtered_df.groupby('ref')['cin'].apply(lambda x: x.notnull().any())

# Step 2: For each patient, check if there is at least one null CIN
has_null = filtered_df.groupby('ref')['cin'].apply(lambda x: x.isnull().any())

# Step 3: Find patients who have both
patients_with_both = has_cin & has_null

# Step 4: Filter the DataFrame to only include those patients
result = filtered_df[filtered_df['ref'].isin(patients_with_both[patients_with_both].index)]

result

          ref      cin
197502  14J10  N398248
200850  14J10  N398248
242396  14J10  N398248
186570  14J10  N398248
238871  14J10  N398248
...       ...      ...
252550  24K50  J172097
252644  24K86  N426270
253449  24K86      NaN
252648  24K90   A23496
253042  24K90      NaN

[91571 rows x 2 columns]

In [772]:
modes_cin = data_patient.groupby('ref')['cin'].agg(
    lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan
)


modes_cin_dict = modes_cin.to_dict()

def fill_phone(row):
  return modes_cin_dict.get(row['ref'] , np.nan)


filtered_df['cin'] = filtered_df.apply(fill_phone , axis=1)
filtered_df[filtered_df['ref']=='24H380']

<ipython-input-772-f413341e7d56>:2: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'bool'
  lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan
<ipython-input-772-f413341e7d56>:2: UserWarning: Unable to sort modes: '<' not supported between instances of 'bool' and 'str'
  lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan

           ref       cin
250257  24H380  DS237172
248380  24H380  DS237172
250123  24H380  DS237172

REPLACIN CIN NOW

In [773]:
data_patient['cin'] = filtered_df['cin'].dropna()

data_patient['cin'][data_patient['ref']=='14K1038']

1102      N132543
10828     N132543
102477    N132543
135541    N132543
144421    N132543
214566    N132543
218964    N132543
Name: cin, dtype: object

In [774]:
def search_telephone(telephone):
  telephone = str(telephone)
  #replace spaces with ''
  telephone = telephone.replace(" " , "")
  #replace alphabetic or punctuation with '' too
  telephone = re.sub('\D+' , '' , telephone )
  pattern_phone = r'(0\d{9})'
  match = re.search(pattern_phone , telephone)
  if match :
    return match.group(1)
  #if number start with +212 6
  match = re.search(r'+' , telephone)
  if match :
    return match.group()
  return telephone

print(search_telephone('gfgfggf06744474 7791033') )
print(search_telephone('gfgfggf06744474 7791033') )
print(search_telephone('gfgfggf+06744474 7791033') )

0674447477
0674447477
0674447477

In [775]:
data_patient['adresse'].head()

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: adresse, dtype: object

In [776]:
from pickle import TRUE
index_fax = telephone_extracted_from_adresse.index.tolist()
index_cin = cin.index.tolist()
cin_fax = index_cin
cin_fax.extend(index_fax)



data_patient['adresse'].drop(cin_fax , axis=0)


def filter_text(text):
    text = str(text).replace(" ", '').upper()

    # CIN pattern: 1 or 2 letters + 6 or 7 digits
    pattern_cin = r'CIN[:\-]?[A-Z]{1,2}\d{4,7}'
    if re.search(pattern_cin, text):
        return True

    # Digits pattern: 5 or more digits
    pattern_digits = r'\d{5,}'
    if re.search(pattern_digits, text):
        return True

    return False



data_patient['cin'] = data_patient['cin'].drop(cin_fax)


mask = data_patient['adresse'].apply(filter_text)
df_cleaned = data_patient[~mask]  # Drop rows where the condition is True

df_cleaned_index = df_cleaned['adresse'].dropna().index

data_patient.loc[~data_patient.index.isin(df_cleaned_index), 'adresse'] = np.nan

data_patient['adresse'].dropna()

912                                        HANCHAN
1380                                 lot5 esaouira
1386                                      KORIMATE
1462                                       MOUARID
1558      02RUE LALLA HASNA LOG DES FONCTIONNAIREZ
                            ...
253530                                  LAHCINATE
253533              16lot economique qu industriel
253541                                   EL BORJ 1
253559                                   608 azlef
253563                              KHIALI MOHAMED
Name: adresse, Length: 41348, dtype: object

cleaning cin

In [777]:
def extract_first_name(text):


  if isinstance(text , str):

      names_morrocain_pattern = r'(^(([A-Za-z]+\s+)?\s*(el|ait|ait sidi|sidi)\s+[A-Z]+))'


      match = re.search(names_morrocain_pattern , text , re.IGNORECASE)
      text_split = text.split()
      if len(text_split)== 2 :
        return (text_split[0])
      elif match :
        return match.group(1)

      elif len(text_split)== 2 :
        return (text_split[0])

      elif len(text_split) ==4 or len(text_split) ==5 :
        return " ".join(text_split[0:len(text_split) -1])

      return text_split[0]

  return text




def extract_last_name(text):


  if isinstance(text , str) :
    names_morrocain_pattern = r'((?:el|ait|sidi|moulay)\s+[A-Za-z]+|[A-Za-z]+)$'


    match = re.search(names_morrocain_pattern , text , re.IGNORECASE)
    text_split = text.split()
    if len(text_split)== 2 :
      return (text_split[1] )
    elif match :
      return match.group(1)

    return text_split[-1]

  return text


print(extract_last_name('EL MASLOHI EL BATOUL') )
print(extract_last_name('EL OUAD MOHAMMED MOUHCINE') )


data_patient['nom'] = data_patient['nomprenom'].apply(extract_first_name)
data_patient['prenom'] = data_patient['nomprenom'].apply(extract_last_name)
#data_patient[['nom' , 'prenom', 'nomprenom']][data_patient['prenom']==False]

EL BATOUL
MOUHCINE

In [778]:
data_patient[['nom' , 'prenom']]

                nom      prenom
0           TRIFHAT        RKIA
1            CHBIKI      SALIMA
2             NAIMI      FATIMA
3          GHASSOUL       ZOHRA
4       EL KHARRIGO     TAOUFIQ
...             ...         ...
253560       KOUISS        HIND
253561      ETTAKNI  ANDELLATIF
253562       CHAPIN      MARCEL
253563       KHIALI   FIRSAOUSS
253564    BOUHADITE       ZAINA

[253565 rows x 2 columns]

testing

In [779]:

def extract_last_name(text):
  names_morrocain_pattern = r'((?:el|ait|sidi|moulay)\s+[A-Za-z]+|[A-Za-z]+)$'


  match = re.search(names_morrocain_pattern , text , re.IGNORECASE)
  text_split = text.split()
  if len(text_split)== 2 :
    return (text_split[1] )
  elif match :
    return match.group(1)



print(extract_last_name('AGOUMAD  MOSTAFA el ahmed') )
print(extract_last_name('BELMAHJOUBI EL MOSTAPHA'))
print(extract_last_name('EL BOHALI EL BATOUL'))

el ahmed
EL MOSTAPHA
EL BATOUL

In [780]:
from shutil import ignore_patterns
data_patient['ba'].value_counts()


def transforming_gender(gender):
  regex_femenun = r'f\w*m'
  regex_masculin = r'mas'

  match_f  = re.search(regex_femenun , gender  , re.IGNORECASE)
  match_m  = re.search(regex_masculin  ,  gender , re.IGNORECASE)
  if match_f :
    return 'F'
  elif match_m :
    return 'M'

  else :
    return 'UNKOWN'




transforming_gender('fem')
data_patient['ba'] =data_patient['ba'].apply(transforming_gender)

data_patient['ba']












#data_patient['ba'].apply(transforming_gender)

0         F
1         F
2         F
3         F
4         F
         ..
253560    F
253561    M
253562    M
253563    F
253564    F
Name: ba, Length: 253565, dtype: object

fixing gender

I found this on names

In [781]:

false_name_format = data_patient[data_patient['prenom'].astype(str).str.contains(r'\d+' , regex =True)]['prenom'].index
data_patient[data_patient['prenom'].astype(str).str.contains(r'\d+' , regex =True)]['prenom']

data_patient['prenom']

0               RKIA
1             SALIMA
2             FATIMA
3              ZOHRA
4            TAOUFIQ
             ...
253560          HIND
253561    ANDELLATIF
253562        MARCEL
253563     FIRSAOUSS
253564         ZAINA
Name: prenom, Length: 253565, dtype: object

In [782]:
data_patient['prenom'].iloc[false_name_format]  = data_patient['prenom'].iloc[false_name_format].apply(lambda x : " ")
#changed false prenom with sace so my model work good for predicting

data_patient[data_patient['prenom'].astype(str).str.contains(r'\d+' , regex =True)]['prenom']

data_patient['prenom']

<ipython-input-782-fa011a279e34>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_patient['prenom'].iloc[false_name_format]  = data_patient['prenom'].iloc[false_name_format].apply(lambda x : " ")

0               RKIA
1             SALIMA
2             FATIMA
3              ZOHRA
4            TAOUFIQ
             ...
253560          HIND
253561    ANDELLATIF
253562        MARCEL
253563     FIRSAOUSS
253564         ZAINA
Name: prenom, Length: 253565, dtype: object

changing this

In [783]:
import pandas as pd
import joblib
import re
from sklearn.metrics import accuracy_score
import numpy as np # Import numpy

# Re-load the model and define helper functions (assuming they are correct)
model = joblib.load('/content/model.joblib')

def data_frame_user(list_names):

    def get_custom_features(list_name):
        ends_with_a = []
        ends_with_ia = []

        for name in list_name:

            if pd.notnull(name) and isinstance(name, str) :
                ends_with_a.append(1 if name.endswith('A') else 0)
                ends_with_ia.append(1 if name.endswith('IA') else 0)
            else:
                # If not a string or NaN, append 0 for both features
                ends_with_a.append(0)
                ends_with_ia.append(0)

        return ends_with_a, ends_with_ia


    new_name_features = get_custom_features(list_names)


    data = []
    for i in range(len(list_names)):
        data.append({
            "Name": list_names[i],
            "ends_with_a": new_name_features[0][i],
            "ends_with_ia": new_name_features[1][i]
        })

    return pd.DataFrame(data)


def gender_prediction_based_on_name(list_names):
  # Ensure list_names does not contain NaN values
  # Replace NaN with empty strings or drop them based on your needs
  cleaned_list_names = ["" if pd.isna(name) else name for name in list_names]

  data = data_frame_user(cleaned_list_names) # Use the cleaned list
  proba = model.predict_proba(data)
  proba_female =  model.predict_proba(data)[:,0]
  df_proba_female = pd.DataFrame(proba_female , columns = ["proba_female"] , index=data.index)
  results = pd.concat([data["Name"] , df_proba_female] , axis = 1)
  results["predicted_gender"] = results["proba_female"].apply(lambda x : "M" if x < 0.63 else "F")
  return results

# Re-create patient_names and clean it
patient_names = data_patient['prenom'].tolist()

# Now, call the function with the potentially large list
data_patient['predicted_gender'] = gender_prediction_based_on_name(patient_names)['predicted_gender']

In [784]:
data_patient['prenom']

0               RKIA
1             SALIMA
2             FATIMA
3              ZOHRA
4            TAOUFIQ
             ...
253560          HIND
253561    ANDELLATIF
253562        MARCEL
253563     FIRSAOUSS
253564         ZAINA
Name: prenom, Length: 253565, dtype: object

In [785]:
from sklearn.metrics import accuracy_score



accuracy = accuracy_score(data_patient['predicted_gender'] , data_patient['ba'])
print(f"the accuracy score is {accuracy}")

mismatches = data_patient[data_patient['predicted_gender'] != data_patient['ba']]
mismatches = mismatches[['nomprenom' , 'prenom', 'predicted_gender', 'ba']]

mismatches.to_excel('mismatches.xlsx')

the accuracy score is 0.9846469347110208

handling time

In [786]:
data_patient['dnaiss'].head(10)

0    01/01/1958
1    04/01/1993
2    01/01/1960
3    12/12/1961
4    30/04/1962
5    01/01/1976
6    01/01/1971
7    14/05/1960
8    01/01/1988
9    22/08/1995
Name: dnaiss, dtype: object

In [787]:
data_patient.columns
print(f"date shape is {data_patient.shape[0]}")
data_patient[['age' , 'dnaiss']][data_patient['dnaiss'].str.contains(r'\d{1,2}/\d{1,2}/\d{4}')]
#extract year from this


data_patient['year_naiss'] = data_patient['dnaiss'].str.extract(r'\d{1,2}/\d{1,2}/(\d{4})').astype(int)


data_patient[['dnaiss' , 'year_naiss']][data_patient['year_naiss'] < 1900 ]

date shape is 253565

            dnaiss  year_naiss
1056    01/11/0195         195
3257    06/03/1697        1697
5682    22/03/0975         975
6918    01/01/1196        1196
9280    01/01/1197        1197
10486   01/01/1198        1198
10665   12/01/1198        1198
11849   24/12/0963         963
12224   29/12/1279        1279
12447   01/01/1193        1193
13359   01/01/1195        1195
17351   01/01/1193        1193
28735   01/01/1196        1196
28761   01/01/1196        1196
33853   01/10/1196        1196
36060   10/10/1197        1197
39084   29/12/1279        1279
39118   01/01/1195        1195
39655   24/12/0963         963
42428   01/01/1197        1197
44306   20/10/1197        1197
44988   01/01/1198        1198
55077   09/01/1197        1197
58029   01/01/1644        1644
69350   15/11/1499        1499
70674   01/01/1198        1198
81677   04/01/1197        1197
82785   01/01/1196        1196
85353   01/01/1195        1195
86701   01/01/1198        1198
104564  01/01/1644        1644
116949  01/01/1685        1685
126124  24/10/1199        1199
148099  26/03/1681        1681
152737  01/01/1193        1193
180403  01/01/1195        1195
182078  09/01/1197        1197
184404  01/01/1197        1197
184719  01/01/1196        1196
187215  01/01/1197        1197
187960  01/01/1195        1195
213118  26/09/1882        1882
216619  01/01/1195        1195
219591  01/01/1195        1195
226902  01/01/1195        1195
230124  27/01/1195        1195
231147  01/01/1196        1196
237841  06/05/0977         977
240715  01/01/1195        1195
251083  01/01/1195        1195

In [788]:
def fix_date(date):
  #first we need to make sure that the date is corrected format
  verify_date = re.search(r'(\d{1,2}/\d{1,2}/\d{3,4})' ,str(date))
  if verify_date:
    date = verify_date.group(1)
    extracted_year  = re.search(r'\d{1,2}/\d{1,2}/(\d{3,4})' , date)
    extracted_year = extracted_year.group(1)

    #veriy if the year have number have issues like thsi 119 -> 1919
    three_digits= re.search(r'^(\d{3})$' , extracted_year)
    if  three_digits  and (int(re.search(r'(\d)\d{2}' , extracted_year).group(1))) < 9  :
        extracted_year = re.sub(r'(\d)(\d)(\d)' , lambda x :  x.group(1)+"m" +  x.group(3)  , extracted_year )
        return re.sub(r'(\d{1,2}/\d{1,2}/)(\d{3})' , lambda x : x.group(1) + str(extracte_year) , date )
    # verify if the year have 9 in the beginning of  3 digits so we will just add 1
    if three_digits and re.search(r'(\d)\d{2}' , extracted_year).group(1) == "9" :
      extracted_year =  "1" + extracted_year
      return re.sub(r'(\d{1,2}/\d{1,2}/)(\d{3})' , lambda x : x.group(1) + str(extracte_year)  , date)




    # verify if the number now have 4 digits





    four_digits = re.search(r'^(\d{4})$' , extracted_year)


    if four_digits and (int(re.search(r'(\d)(\d)(\d{2})', extracted_year).group(2)) < 9 and int(re.search(r'(\d)(\d{3})', extracted_year).group(1)) != 1):
         # Replace first digit with '1' and second with '9' in one go
         extracted_year = re.sub(r'^(\d)(\d)(\d{2})$', lambda x: '1' + '9' + x.group(3), extracted_year)
         return re.sub(r'(\d{1,2}/\d{1,2}/)(\d{4})', lambda x: x.group(1) + extracted_year, date)

    if  four_digits and (   (int(re.search(r'(\d)(\d{3})' , extracted_year).group(1) )) !=1 ):
      extracted_year = re.sub(r'(\d)(\d{3})' ,lambda x : "1" + x.group(2) , extracted_year)
      return re.sub(r'(\d{1,2}/\d{1,2}/)(\d{4})' , lambda x : x.group(1) + str(extracted_year) , date )


    if   four_digits and  (int(re.search(r'(\d)(\d)(\d{2})' , extracted_year).group(2) )) < 9 :
       extracted_year = re.sub(r'(\d)(\d)(\d{2})' ,lambda x : x.group(1) + "9"  + x.group(3) , extracted_year)
       return re.sub(r'(\d{1,2}/\d{1,2}/)(\d{4})' , lambda x : x.group(1) + str(extracted_year) , date )



    return date
fix_date('hdh	01/01/1955hdhshs7')

test = data_patient[['dnaiss' , 'year_naiss']][data_patient['year_naiss'] < 1900 ]

test['after_fix_date'] = test['dnaiss'].apply(fix_date)

#fix_date('hdh	01/11/0195hdhshs7')


test

            dnaiss  year_naiss after_fix_date
1056    01/11/0195         195     01/11/1995
3257    06/03/1697        1697     06/03/1997
5682    22/03/0975         975     22/03/1975
6918    01/01/1196        1196     01/01/1996
9280    01/01/1197        1197     01/01/1997
10486   01/01/1198        1198     01/01/1998
10665   12/01/1198        1198     12/01/1998
11849   24/12/0963         963     24/12/1963
12224   29/12/1279        1279     29/12/1979
12447   01/01/1193        1193     01/01/1993
13359   01/01/1195        1195     01/01/1995
17351   01/01/1193        1193     01/01/1993
28735   01/01/1196        1196     01/01/1996
28761   01/01/1196        1196     01/01/1996
33853   01/10/1196        1196     01/10/1996
36060   10/10/1197        1197     10/10/1997
39084   29/12/1279        1279     29/12/1979
39118   01/01/1195        1195     01/01/1995
39655   24/12/0963         963     24/12/1963
42428   01/01/1197        1197     01/01/1997
44306   20/10/1197        1197     20/10/1997
44988   01/01/1198        1198     01/01/1998
55077   09/01/1197        1197     09/01/1997
58029   01/01/1644        1644     01/01/1944
69350   15/11/1499        1499     15/11/1999
70674   01/01/1198        1198     01/01/1998
81677   04/01/1197        1197     04/01/1997
82785   01/01/1196        1196     01/01/1996
85353   01/01/1195        1195     01/01/1995
86701   01/01/1198        1198     01/01/1998
104564  01/01/1644        1644     01/01/1944
116949  01/01/1685        1685     01/01/1985
126124  24/10/1199        1199     24/10/1999
148099  26/03/1681        1681     26/03/1981
152737  01/01/1193        1193     01/01/1993
180403  01/01/1195        1195     01/01/1995
182078  09/01/1197        1197     09/01/1997
184404  01/01/1197        1197     01/01/1997
184719  01/01/1196        1196     01/01/1996
187215  01/01/1197        1197     01/01/1997
187960  01/01/1195        1195     01/01/1995
213118  26/09/1882        1882     26/09/1982
216619  01/01/1195        1195     01/01/1995
219591  01/01/1195        1195     01/01/1995
226902  01/01/1195        1195     01/01/1995
230124  27/01/1195        1195     27/01/1995
231147  01/01/1196        1196     01/01/1996
237841  06/05/0977         977     06/05/1977
240715  01/01/1195        1195     01/01/1995
251083  01/01/1195        1195     01/01/1995

the function literaly clean everything about the date

In [789]:
data_patient['dnaiss'] = data_patient['dnaiss'].apply(fix_date)

In [790]:
#transforming into -> 24/12/1963 - > YYYY-MM-DD



data_patient['dnaiss'] = pd.to_datetime(data_patient['dnaiss']  , format="%d/%m/%Y", errors='coerce')

data_patient['dnaiss'].dt.year

0         1958.0
1         1993.0
2         1960.0
3         1961.0
4         1962.0
           ...
253560    1992.0
253561    1982.0
253562    1947.0
253563    1911.0
253564    1966.0
Name: dnaiss, Length: 253565, dtype: float64

Moamuna said  : Combiner les commentaires?

In [791]:

data_patient[['observ' , 'comment1' , 'comment2']] = data_patient[['observ' , 'comment1' , 'comment2']].fillna("")
data_patient['total_comment'] = data_patient[['observ' , 'comment1' , 'comment2']].apply(
    lambda row : f"{row['observ']} {row['comment1']} {row['comment2']}" , axis=1 )
# observ , comment1 , comment2

data_patient['total_comment']

0         TRAITEMENT ?: SINTROM,
1              Grossesse ?: OUI,
2
3
4
                    ...
253560
253561             Abstinence: ,
253562
253563
253564
Name: total_comment, Length: 253565, dtype: object

In [792]:
data_patient['telephone']

0                NaN
1         0607098707
2         0666014056
3                NaN
4         0666155610
             ...
253560    0699334313
253561           NaN
253562    0648816169
253563           NaN
253564    0677787961
Name: telephone, Length: 253565, dtype: object

In [793]:
valid_cin = data_patient['cin'].notna()
data_patient['cin'][valid_cin]

1         J485388
2         N105701
9         N398248
14         N51316
18        N196554
           ...
253544     N30474
253547     N94479
253550     N31077
253559    N226101
253564    J282843
Name: cin, Length: 80403, dtype: object

In [794]:
data_patient['telephone'] = data_patient['telephone'].astype(str)
data_patient['telephone'].dtype
data_patient.to_csv('data_patient_cleaned.csv' , index=True )

In [795]:

data_patient['telephone'] = data_patient['telephone'].apply(lambda x : np.nan if x =='nan' else x )
not_phone = data_patient['telephone'].dropna().apply(search_fax)
index_not_phone = not_phone[~not_phone].index
data_patient['telephone'].iloc[index_not_phone]

620             06
659       26111955
1335            06
1646        062521
1705          0600
            ...
251066          06
251319          06
251430        0667
252238          06
253306          06
Name: telephone, Length: 566, dtype: object

dropped non phone seccusefuly

In [796]:
data_patient['telephone'] = data_patient['telephone'].iloc[index_not_phone].apply(lambda x : np.nan)

removing non cin

In [797]:
non_cin  = data_patient['cin'].dropna().apply(search_cin)
'''non_cin_index = non_cin[~non_cin].index
data_patient['cin'] = data_patient['cin'].iloc[non_cin_index].apply(lambda x : np.nan)


data_patient['cin'].dropna()'''
data_patient['cin'].dropna().apply(search_cin)

1         True
2         True
9         True
14        True
18        True
          ...
253544    True
253547    True
253550    True
253559    True
253564    True
Name: cin, Length: 80403, dtype: bool

In [806]:
non_cin

Index([], dtype='int64')